### ISSUE TITLE
Contract factory cannot be used in blockpapps.. block server crashes on POST 

### ISSUE THREAD

**Issue by ketankalia** [blockapps/issues#2]
This is the smart contract code I was trying to run
```
contract Factory {
  bytes32[] Names;
  address[] newContracts;
  function createContract (bytes32 name) {
    address newContract = new Contract(name);
    newContracts.push(newContract);
  } 

  function getName (uint i) {
    Contract con = Contract(newContracts[i]);
    Names[i] = con.Name();
  }
}

contract Contract {
  bytes32 public Name;
  function Contract (bytes32 name) {
    Name = name;
  }
}
```

Steps to reproduce :-
 Prerequsite- get lates npm packages since date 6/11/2016
1. Start block server on local server
2. Just compile and upload this contract to blockapps (I am runing in localserver mode with api pointed to strato)
3. Go to localhost:8000 (default setup, your port might be different)
4. Then http://localhost:8000 /contracts/ 
5. Click on 'Generated' HTML link for the address of Factory contract
6. Enter relevant values in set method on UI and press the method to post it

Observed:
block server crashes after message 'trying to invoke contract and args

Expected:
block server should not crash

**Comment by ryanreich** [comment]
The root cause of the problem you're seeing is that `createContract()` takes a `bytes32`, which `bloc` expects to be supplied as an actual hex-encoded string of 32 bytes (that is, 64 hexadecimal digits).  You will almost certainly have been entering the name as a UTF8 string, which is an error.  (Still, bloc shouldn't crash.)

The reason we can't support using `bytes32` as strings even though this is recommended by certain out-of-date online examples is that the type is _intended_ to hold actual strings of bytes, and there is no way of distinguishing "deadbeef" as a UTF8 string versus a hex string.  Therefore, we recommend that you use the type intended to hold text: `string`.

Let me propose a rewriting of your contracts that should work.
```
contract Factory {
  string[] Names;
  address[] newContracts;
  function createContract (string name) {
    address newContract = new Contract(name);
    newContracts.push(newContract);
    Names.push(name);
  } 
}

contract Contract {
  string Name;
  function Contract (string name) {
    Name = name;
  }
}
```

I made the following changes:

 - `bytes32` became `string`, of course.
 - I removed the `public` keyword from the `Name` variable.  Unless you are intending to inherit from `Contract` this modifier is meaningless.
 - I also removed the use of the accessor function `Name()` in favor of storing the provided name directly.  Although there is probably a situation where this kind of construct is important (for example, if `Contract` were to store a computed value in its state variables and you wanted to read it), right now, it is needless work.  Also, I found that `solc` rejected the construct `Names[i] = con.Name();` with what looks like a buggy type error.

Hope this helps!
